### ISSUE TITLE
Pick and set up a subdomain for this to live at

### ISSUE THREAD

**Issue by emma-sg** [webrecorder/create-archive-now#20]
Options from chat:
- `archivenow.webrecorder.net`
- `archive-now.webrecorder.net`
- [x] `create.webrecorder.net`

### Tasks

- [x] Pick a domain
- [x] Update GitHub Pages settings for this repo, and DNS if necessary
  - @ikreymer I can do this for you if you give me admin perms for this repo, otherwise you'll need to do it yourself
- [x] Update sitemap and CTA redirect in https://github.com/webrecorder/website
